import Head from "next/head";
import Image from "next/image";
import certificate from "../public/Certificate.jpg";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { PDFDocument, rgb, cmyk } from "pdf-lib";
import fontkit from "@pdf-lib/fontkit";

export default function Home() {
  const [name, setName] = useState("");
  const [fontSize, setFontsize] = useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Certificate Generate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p>Certificate Generate</p>
        <p>{name}</p>
        <>
          <label>Name :</label>
          <input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
          <label>Size of text`( must be 0-100)` :</label>
          <input
            type="number"
            value={fontSize}
            onChange={(e) => setFontsize(e.target.value)}
          />
        </>
        <button
          onClick={async () => {
            console.log(name);
            const pdfDoc = await PDFDocument.create();

            const fontBytes = await fetch(
              // "https://cdn.jsdelivr.net/npm/font-th-sarabun-new@1.0.0/fonts/THSarabunNew-webfont.ttf"
              // "https://cdn.jsdelivr.net/npm/@openfonts/prompt_thai@1.44.1/files/prompt-thai-400.woff"
              // "https://cdn.jsdelivr.net/npm/@fontsource/ibm-plex-sans-thai@4.5.11/files/ibm-plex-sans-thai-all-400-normal.woff"
              "https://cdn.jsdelivr.net/npm/@fontsource/noto-sans-thai@4.5.12/files/noto-sans-thai-all-400-normal.woff"
            ).then((res) => res.arrayBuffer());

            const jpgImageBytes = await fetch(
              certificate.src // path to your image
            ).then((res) => {
              console.log("jpgImageBytes", certificate.src);
              return res.arrayBuffer();
            });

            pdfDoc.registerFontkit(fontkit);
            const customFont = await pdfDoc.embedFont(fontBytes);

            const jpgImage = await pdfDoc.embedJpg(jpgImageBytes);
            const jpgDims = jpgImage.scale(0.5);

            const page = pdfDoc.addPage([jpgDims.width, jpgDims.height]);

            page.drawImage(jpgImage, {
              x: 0,
              y: 0,
              width: jpgDims.width,
              height: jpgDims.height,
            });
            let some = name.split(" ");
            page.drawText(name, {
              x:
                page.getWidth() / 2 - some[0].length * (parseInt(fontSize) / 2.2),
              y: page.getHeight() / 2 - parseInt(fontSize) / 1.5,
              size: parseInt(fontSize),
              font: customFont,
              // font: timesRomanFont,
              // color: rgb(6, 57, 112),
              color: cmyk(0.64, 0.73, 0, 0.69),
            });
            const pdfBytes = await pdfDoc.save();
            const pdf = document.createElement("a");
            pdf.href = URL.createObjectURL(
              new Blob([pdfBytes], { type: "application/pdf" })
            );
            pdf.download = `${name}-certificate.pdf`;
            pdf.click();
          }}
        >
          Submit
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
