import Head from "next/head";
import Image from "next/image";
import certificate from "../public/Certificate.jpg";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { PDFDocument, rgb } from "pdf-lib";
import fontkit from "@pdf-lib/fontkit";

export default function Home() {
  const [name, setName] = useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Certificate Generate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p>Certificate Generate</p>
        <p>{name}</p>
        <>
          <label>Name :</label>
          <input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
        </>
        <button
          onClick={async () => {
            console.log(name);
            const pdfDoc = await PDFDocument.create();

            const fontBytes = await fetch(
              "https://cdn.jsdelivr.net/npm/font-th-sarabun-new@1.0.0/fonts/THSarabunNew-webfont.ttf"
            ).then((res) => res.arrayBuffer());

            const jpgImageBytes = await fetch(
              certificate.src // path to your image
            ).then((res) => {
              console.log("jpgImageBytes", certificate.src);
              return res.arrayBuffer();
            });

            pdfDoc.registerFontkit(fontkit);
            const customFont = await pdfDoc.embedFont(fontBytes);

            const jpgImage = await pdfDoc.embedJpg(jpgImageBytes);
            const jpgDims = jpgImage.scale(0.5);

            const page = pdfDoc.addPage([jpgDims.width, jpgDims.height]);

            page.drawImage(jpgImage, {
              x: 0,
              y: 0,
              width: jpgDims.width,
              height: jpgDims.height,
            });
            const fontSize = 48;
            page.drawText(name, {
              x:
                name.length > 10
                  ? page.getWidth() / 2.5
                  : page.getWidth() / 2 - fontSize / 3,
              y: page.getHeight() / 2 - fontSize / 3,
              size: fontSize,
              font: customFont,
              // font: timesRomanFont,
              color: rgb(0, 0.53, 0.71),
            });
            const pdfBytes = await pdfDoc.save();
            const pdf = document.createElement("a");
            pdf.href = URL.createObjectURL(
              new Blob([pdfBytes], { type: "application/pdf" })
            );
            pdf.download = "certificate.pdf";
            pdf.click();
          }}
        >
          Submit
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
